src/Pms/CoreBundle/Entity/PurchaseOrderItem.php
<?php

namespace Pms\CoreBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Pms\SettingBundle\Entity\Item;
use Pms\SettingBundle\Entity\Project;

/**
 * PurchaseOrderItem
 *
 * @ORM\Table(name="purchase_order_items")
 * @ORM\Entity(repositoryClass="Pms\CoreBundle\Entity\Repository\PurchaseOrderItemRepository")
 */
class PurchaseOrderItem
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Item
     *
     * @ORM\ManyToOne(targetEntity="Pms\SettingBundle\Entity\Item", inversedBy="purchaseOrderItem", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="items", nullable=true)
     */
    private $item;

    /**
     * @var Project
     *
     * @ORM\ManyToOne(targetEntity="Pms\SettingBundle\Entity\Project", inversedBy="purchaseOrderItem", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="projects", nullable=true)
     */
    private $project;

    /**
     * @var float
     *
     * @ORM\Column(name="quantities", type="float", nullable=true)
     */
    private $quantity;

    /**
     * @var float
     *
     * @ORM\Column(name="total_order_receive_quantity", type="float", nullable=true)
     */
    private $totalOrderReceiveQuantity;

    /**
     * @var PurchaseOrder
     *
     * @ORM\ManyToOne(targetEntity="Pms\CoreBundle\Entity\PurchaseOrder", inversedBy="purchaseOrderItems", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="purchase_orders", nullable=true)
     */
    private $purchaseOrder;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Pms\CoreBundle\Entity\ReceivedItem", mappedBy="purchaseOrderItem", cascade={"persist", "remove"})
     */
    private $receivedItems;

    /**
     * @var PurchaseRequisitionItem
     *
     * @ORM\ManyToOne(targetEntity="Pms\CoreBundle\Entity\PurchaseRequisitionItem", inversedBy="purchaseOrderItems", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="purchase_requisition_item", nullable=true)
     */
    private $purchaseRequisitionItem;

    /**
     * @ORM\OneToOne(targetEntity="PurchaseOrderItemClose", mappedBy="purchaseOrderItem", cascade={"persist"})
     *
     */
    protected $purchaseOrderItemClose;

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="integer", nullable=true)
     */
    private $status;

    /**
     * @var integer
     *
     * @ORM\Column(name="amendment", type="integer")
     */
    private $amendment;

    /**
     * @var float
     *
     * @ORM\Column(name="amendment_quantity", type="float", nullable=true)
     */
    private $amendmentQuantity;

    /**
     * @var integer
     *
     * @ORM\Column(name="amendment_ref", type="integer", nullable=true)
     */
    private $amendmentRef;

    /**
     * @var integer
     *
     * @ORM\Column(name="amendment_ref_po", type="integer", nullable=true)
     */
    private $amendmentRefPo;

    /**
     * @var integer
     *
     * @ORM\Column(name="approval_status", type="integer", nullable=true)
     */
    private $approvalStatus;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float", nullable=true)
     */
    private $price;

    /**
     * @var string
     *
     * @ORM\Column(name="brand", type="string", length=255, nullable=true)
     */
    private $brand;
    /**
     * @var string
     *
     * @ORM\Column(name="remark", type="string", length=255, nullable=true)
     */
    private $remark;

    /**
     * @var float
     *
     * @ORM\Column(name="amount", type="float", nullable=true)
     */
    private $amount;

    public function __construct()
    {
        $this->receivedItems = new ArrayCollection();
    }

    public function addReceivedItem(ReceivedItem $item)
    {
        $item->setPurchaseOrderItem($this);

        if (!$this->getReceivedItems()->contains($item)) {
            $this->receivedItems->add($item);
        }

        return $this;
    }

    public function removeReceivedItem(ReceivedItem $item)
    {
        if ($this->getReceivedItems()->contains($item)) {
            $this->getReceivedItems()->removeElement($item);
        }
    }

    public function getReceivedItems()
    {
        return $this->receivedItems;
    }

    /**
     * Set totalOrderReceiveQuantity
     *
     * @param float $totalOrderReceiveQuantity
     * @return PurchaseOrderItem
     */
    public function setTotalOrderReceiveQuantity($totalOrderReceiveQuantity)
    {
        $this->totalOrderReceiveQuantity = $totalOrderReceiveQuantity;

        return $this;
    }

    /**
     * Get totalOrderReceiveQuantity
     *
     * @return float
     */
    public function getTotalOrderReceiveQuantity()
    {
        return $this->totalOrderReceiveQuantity;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set quantity
     *
     * @param float $quantity
     * @return PurchaseOrderItem
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set purchaseOrder
     *
     * @param PurchaseOrder $purchaseOrder
     * @return PurchaseOrderItem
     */
    public function setPurchaseOrder($purchaseOrder)
    {
        $this->purchaseOrder = $purchaseOrder;

        return $this;
    }

    /**
     * Get purchaseOrder
     *
     * @return PurchaseOrder
     */
    public function getPurchaseOrder()
    {
        return $this->purchaseOrder;
    }

    /**
     * Set item
     *
     * @param Item $item
     * @return PurchaseOrderItem
     */
    public function setItem($item)
    {
        $this->item = $item;

        return $this;
    }

    /**
     * Get item
     *
     * @return Item
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return PurchaseOrderItem
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set amendment
     *
     * @param integer $amendment
     * @return PurchaseOrderItem
     */
    public function setAmendment($amendment)
    {
        $this->amendment = $amendment;

        return $this;
    }

    /**
     * Get amendment
     *
     * @return integer
     */
    public function getAmendment()
    {
        return $this->amendment;
    }

    /**
     * Set amendmentQuantity
     *
     * @param float $amendmentQuantity
     * @return PurchaseOrderItem
     */
    public function setAmendmentQuantity($amendmentQuantity)
    {
        $this->amendmentQuantity = $amendmentQuantity;

        return $this;
    }

    /**
     * Get amendmentQuantity
     *
     * @return float
     */
    public function getAmendmentQuantity()
    {
        return $this->amendmentQuantity;
    }

    /**
     * Set amendmentRef
     *
     * @param integer $amendmentRef
     * @return PurchaseOrderItem
     */
    public function setAmendmentRef($amendmentRef)
    {
        $this->amendmentRef = $amendmentRef;

        return $this;
    }

    /**
     * Get amendmentRef
     *
     * @return integer
     */
    public function getAmendmentRef()
    {
        return $this->amendmentRef;
    }

    /**
     * Set amendmentRefPo
     *
     * @param integer $amendmentRefPo
     * @return PurchaseOrderItem
     */
    public function setAmendmentRefPo($amendmentRefPo)
    {
        $this->amendmentRefPo = $amendmentRefPo;

        return $this;
    }

    /**
     * Get amendmentRefPo
     *
     * @return integer
     */
    public function getAmendmentRefPo()
    {
        return $this->amendmentRefPo;
    }

    /**
     * Set approvalStatus
     *
     * @param integer $approvalStatus
     * @return PurchaseOrderItem
     */
    public function setApprovalStatus($approvalStatus)
    {
        $this->approvalStatus = $approvalStatus;

        return $this;
    }

    /**
     * Get approvalStatus
     *
     * @return integer
     */
    public function getApprovalStatus()
    {
        return $this->approvalStatus;
    }

    /**
     * Set project
     *
     * @param Project $project
     * @return PurchaseOrderItem
     */
    public function setProject($project)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @return \Pms\CoreBundle\Entity\PurchaseRequisitionItem
     */
    public function getPurchaseRequisitionItem()
    {
        return $this->purchaseRequisitionItem;
    }

    /**
     * @param \Pms\CoreBundle\Entity\PurchaseRequisitionItem $purchaseRequisitionItem
     * @return $this
     */
    public function setPurchaseRequisitionItem($purchaseRequisitionItem)
    {
        $this->purchaseRequisitionItem = $purchaseRequisitionItem;
        $this->item = $purchaseRequisitionItem->getItem();
        $this->project = $purchaseRequisitionItem->getPurchaseRequisition()->getProject();
        return $this;
    }

    public function getItemName()
    {
        $this->item->getItemName();
    }

    /**
     * Get price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set price
     *
     * @param float $price
     * @return PurchaseOrderItem
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * Get amount
     *
     * @return float
     */

src/Pms/CoreBundle/Form/PurchaseOrderType.php
<?php

namespace Pms\CoreBundle\Form;

use Pms\SettingBundle\Entity\Repository\PurchaseTypeRepository;
use Pms\SettingBundle\Entity\Repository\VendorRepository;
use Pms\UserBundle\Entity\Repository\UserRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToStringTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class PurchaseOrderType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('refNo', 'text',array(
                'attr' => array(
                    'autocomplete' => 'off'
                )
            ))
            ->add('tax', 'text')
            ->add('paymentType', 'choice', array(
                'empty_value' => 'Select payment type',
                'choices' => array(
                    'After delivery payment' => 'After delivery payment',
                    'Advance payment' => 'Advance payment',
                    'Cash payment' => 'Cash payment',
                    'Cash On Delivery Payment' => 'Cash On Delivery Payment'
                )
            ))
            ->add('paymentFrom', 'text',array(
                'read_only'=>true
            ))
            ->add('computationStatus', 'choice', array(
                'empty_value' => 'Select one',
                'choices' => array(
                    1 => 'Yes',
                    2 => 'No'
                )
            ))
            ->add('vendorQuotationReferenceNumber', 'text')
            ->add('file', 'file')
            ->add('fileTwo', 'file')
            ->add('netTotal', 'text', array(
                'attr' => array(
                    'placeholder' => 'Net Total'
                ),
                'read_only' => true
            ))
            ->add('subTotal', 'text', array(
                'attr' => array(
                    'placeholder' => 'Sub Total'
                ),
                'read_only' => true
            ))
            ->add('poNonpo', 'entity', array(
                'class' => 'PmsSettingBundle:PurchaseType',
                'property' => 'name',
                'required' => false,
                'attr' => array(
                    'placeholder' => 'Select Purchase Type'
                ),
                'empty_data' => null,
                'query_builder' => function (PurchaseTypeRepository $repository)
                {
                        return $repository->createQueryBuilder('pt')
                            ->andWhere("pt.status = 1")
                            ->orderBy('pt.name','ASC');
                }
            ))
            ->add('paymentMethod', 'choice', array(
                'empty_value' => 'Select payment method',
                'choices' => array(
                    'Cash' => 'Cash',
                    'Cheque' => 'Cheque',
                )
            ))
            ->add('comment', 'textarea')
            ->add('customTermCondition', 'textarea')
            ->add($builder->create('dateOfDelivered', 'text', array(
                'attr' => array(
                    'placeholder' => 'Date'
                ),
                'data_class' => null,
                'read_only' => true
            ))->addViewTransformer(new DateTimeToStringTransformer(null, null, 'Y-m-d')))
            ->add('purchaseOrderItems', 'collection', array(
                'type' => new PurchaseOrderItemType(),
                'allow_add'    => true,
                'allow_delete' => true,
                'prototype' => true,
                'label_attr' => array(
                    'class' => 'hidden'
                )
            ))
            ->add('buyer', 'entity', array(
                'class' => 'UserBundle:User',
                'property' => 'username',
                'required' => false,
                'attr' => array(
                    'placeholder' => ' Select Buyer'
                ),
                'empty_data' => null,
                'query_builder' => function (UserRepository $repository)
                {
                    return $repository->createQueryBuilder('u')
                        ->join('u.groups', 'g')
                        ->where("g.roles LIKE '%ROLE_BUYER_USERS%'")
                        ->andWhere('u.enabled = 1')
                        ->orderBy('u.username', 'ASC');
                }
            ))
            ->add('vendor', 'entity', array(
                'class' => 'PmsSettingBundle:Vendor',
                'property' => 'vendorName',
                'required' => false,
                'attr' => array(
                    'placeholder' => ' Select Vendor'
                ),
                'empty_data' => null,
                'query_builder' => function (VendorRepository $repository)
                {
                    return $repository->createQueryBuilder('v')
                        ->where('v.status = 1')
                        ->orderBy('v.vendorName', 'ASC');
                }
            ))
            ->add('advancePaymentAmount', 'text')
            ->add('submit', 'submit');
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Pms\CoreBundle\Entity\PurchaseOrder'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'purchaseorder';
    }
}

src/Pms/CoreBundle/Resources/views/PurchaseOrder/itemDetails.html.twig
{% block body %}

    <div class="modal-dialog" style="width: 1000px;">
    <div class="modal-content">
    <div class="modal-header" style="background: lightgrey;">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title bold" style="text-align: center;">Last Item Details</h4>
    </div>

    <div class="col-md-12">
    <table>
    <tr>
        <td>
            <table class="col-md-6" style="margin-top: 10px;padding-top:20px;float: left;">
                <tr>
                    <td style="width: 115px;">
                        {% if  po.vendor != null %}
                            Vendor :
                        {% endif %}
                    </td>
                    <td>
                        {% if  po.vendor != null %}
                            <span style="font-weight: bold;">{{ po.vendor.vendorName | default() }}</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td style="width: 115px;">
                        {% if  po.vendor != null %}
                            Contact Person :
                        {% endif %}
                    </td>
                    <td>
                        {% if  po.vendor != null %}
                            <span style="font-weight: bold;">{{ po.vendor.contractPerson | default() }}</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td style="width: 115px;">
                        {% if  po.vendor != null %}
                            Mobile :
                        {% endif %}
                    </td>
                    <td>
                        {% if  po.vendor != null %}
                            <span style="font-weight: bold;">{{ po.vendor.contractNo | default() }}</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td style="width: 115px;">
                        {% if  po.vendor != null %}
                            Address :
                        {% endif %}
                    </td>
                    <td>
                        {% if  po.vendor != null %}
                            <span style="font-weight: bold;">{{ po.vendor.vendorAddress | default() }}</span>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td style="width: 1000px;">
            <table id="table_order" class="table col-md-12" style="border: 1px solid ghostwhite;">
                <thead style="background:#4b8df8;">
                <tr>
                    <th class="col-md-2" style="padding-left: 15px;">Particulars</th>
                    <th class="col-md-2" style="">Quantity</th>
                    <th class="col-md-2" style="">Price</th>
                </tr>
                </thead>

                <tbody>
                {% for poitem in poi %}
                    <tr>
                        <td style="padding-left: 15px;">
                            {{ poitem.item.itemName }}
                        </td>
                        <td style="padding-left: 15px;">
                            {{ poitem.quantity }}
                        </td>
                        <td style="width: 120px;padding-left: 10px! important;">
                            {{ poitem.price|number_format(2, '.', ',') }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </td>
    </tr>
    </table>
    </div>

    <div class="modal-footer" style="width: 100%;background: lightgrey;">
        <button type="button" class="btn" style="width: 100px;background: #0353D6; color: white !important;"
                data-dismiss="modal">Close
        </button>
    </div>

    </div>
    </div>

{% endblock %}

src/Pms/CoreBundle/Resources/views/PurchaseOrder/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">
                Purchase Order
                <small></small>
            </h3>
            <ul class="page-breadcrumb breadcrumb" style="height: 36px;">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="{{ path('homepage') }}" style="color: #333 !important;">Home</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="{{ path('purchase_order') }}" style="color: #333 !important;">Purchase Order</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#" style="color: #333 !important;">Item List</a>
                </li>
                <li class="pull-right">
                    <div id="" class="" data-placement="" style="font-family: 'Open Sans', sans-serif; color: #f5f5f5; padding-top: 8px;text-align: center;margin-top: -8px;width: 124%;background: #e02222;height: 36px;">
                        <i class="fa fa-calendar"></i>
                        {{ "now"|date("d-F-Y") }}
                    </div>
                </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">
    <div class="modal-dialog" style="width: 100%; padding: 0;">
        <div class="modal-content">
            <div class="modal-header" style="background: lightgrey;">
                <h4 class="modal-title bold" style="text-align: center;"> Open Item List</h4>
            </div>
            <form method="post" action="">
                <div class="modal-body">
                    <div class="row">

                        <div class="col-md-12">

                            <div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                <button type="submit" class="btn" style="font-family: 'Open Sans', sans-serif;width: 100px;background: #0353D6; color: white !important;">
                                    Next <i class="fa icon-next"></i>
                                </button>
                            <table class="table table-striped table-hover dataTable" id="listPo"
                                   aria-describedby="sample_1_info">
                                <thead style="background: #4b8df8;">
                                <tr role="row">
                                    <th>Sl</th>
                                    <th><i class="fa fa-check"></i></th>
                                    <th class="col-md-2">Particulars</th>
                                    <th class="col-md-1">PRQty</th>
                                    <th class="col-md-1">OrderedQty</th>
                                    <th class="col-md-1">RemainQty</th>
                                    <th class="col-md-2">ProjectName</th>
                                    <th class="col-md-1">OrderedBy</th>
                                    <th class="col-md-1">CreatedDate</th>
                                    <th class="col-md-2">ReqDate</th>
                                    <th class="col-md-1">PR No</th>
                                    <th class="col-md-1"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% set i = 0 %}
                                {% for orderItem in pri %}

                                    {% set quantityRequisition = orderItem.quantity %}
                                    {% set quantityOrder = orderItem.purchaseOrderQuantity %}
                                    {% set quantityNeed = quantityRequisition - quantityOrder %}
                                    
                                    {% set i = i + 1 %}
                                        <tr class="po-tr-{{ orderItem.purchaseRequisition.project.projectCategory.id }}">
                                            <td>{{ i }}.</td>
                                        <td>
                                            <input class="po-checkbox" data-po="{{ orderItem.purchaseRequisition.project.projectCategory.id }}" type="checkbox" name="items[]" value="{{ orderItem.id }}">
                                        </td>
                                        <td>
                                            {{ orderItem.item.itemName }}
                                        </td>
                                        <td>
                                            {{ orderItem.quantity|number_format(2, '.', ',') }}{{ orderItem.item.itemUnit }}
                                        </td>
                                        <td>
                                            {{ orderItem.purchaseOrderQuantity|number_format(2, '.', ',') }}{{ orderItem.item.itemUnit }}
                                        </td>
                                        <td>
                                            {{ quantityNeed|number_format(2, '.', ',') }}{{ orderItem.item.itemUnit }}
                                        </td>
                                        <td>
                                            {{ orderItem.purchaseRequisition.project.projectName | default() }}
                                        </td>
                                        <td>
                                            {{ orderItem.purchaseRequisition.createdBy.username | default() }}
                                        </td>
                                        <td>
                                            {{ orderItem.purchaseRequisition.createdDate | date('d M Y') }}
                                        </td>
                                        <td>
                                            {{ orderItem.dateOfRequired | date('d M Y') }}
                                        </td>
                                        <td>
                                            {{ orderItem.purchaseRequisition.id | default() }}
                                        </td>
                                        <td>

                                            {% if (is_granted("ROLE_SUPER_ADMIN") or
                                                  is_granted("ROLE_PR_ITEM_CLOSE_HEAD_OFFICE") or
                                                  is_granted("ROLE_PR_ITEM_CLOSE_LOCAL_OFFICE")) %}

                                            <a href="/purchase-order/item-close/{{ orderItem.id }}"
                                               data-target="#ajax" data-toggle="modal"
                                               class=" btn blue btn-xs mini modal-details displayForDesktop"
                                               style="margin-top:3px;width: 130px;color:#ffffff !important;">close</a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="modal-footer" style="background: lightgrey;">
                    <div class="btn-group">
                        <button type="submit" class="btn" style="font-family: 'Open Sans', sans-serif;width: 100px;background: #0353D6; color: white !important;">
                            Next <i class="fa icon-next"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
</div>

{% endblock %}

{% block documentready %}
    {#<script>#}
    {{ parent() }}
        $('#listPo').dataTable( {
            iDisplayLength: -1,
            bPaginate:false,
            bLengthChange:false,
            bInfo:false
        } );

    var $table = $("#listPo tbody");
    $table.on("change", ".po-checkbox", function(){
        var el = $(this);
        var po = el.data("po");
        var chosen = $table.find('tr.po-tr-'+po + " input:checked");

        if(el.prop('checked')) {
            $table.find('tr').hide();
            $table.find('tr.po-tr-'+po).show();
        }else if(chosen.length == 0){
            $table.find('tr').show();
        }
    });

    {% endblock %}

src/Pms/CoreBundle/Resources/views/PurchaseOrder/purchaseOrderitemClose.html.twig
{% block body %}

          id="po-comment-form">
        <div id="reload-all-po">
            <div class="modal-dialog " style="width:70%;">
                <div class="modal-content">
                    <form action="{{ path('purchase_order_item_close',{id:purchaseRequisitionId}) }}" method="post">
                    <div class="modal-header" style="background: lightgrey;">
                        <button type="button" class="close close-modal-refresh" data-dismiss="modal"
                                aria-hidden="true"></button>
                        <h4 class="modal-title bold" style="text-align: center;">Close Status</h4>
                    </div>
                        <div class="modal-body">
                    <div class="row">

                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="col-md-4 control-label" style="margin-left:15px;">Close Remarks:</label>
                                <div class="col-md-6">
                                    <textarea class="post-comment" name="close-remark" id="commentPo"></textarea>
                                </div>
                            </div>
                            <div class="form-group">


                            </div>
                            {#<div class="form-group">
                                <label class="col-md-4 control-label" style="margin-left: 15px;">Status:</label>
                                <div class="col-md-6">
                                    <div class="radio-list" style="margin-left:16px;">
                                        <label class="radio-inline">
                                            <input type="radio" name="closeStatus" id="rc" value="2" checked> Regular Close </label>
                                        <label class="radio-inline">
                                            <input type="radio" name="closeStatus" id="pc" value="7"> Permanent Close </label>
                                    </div>
                                </div>
                            </div>#}

                            <div class="col-md-6">

                            </div>
                        </div>
                        {#</div>#}
                        <div class="clearfix"></div>

                    </div>

                    </div>
                        <div class="modal-footer" style="background: lightgrey;">
                            <div class="btn-group">
                                <button type="submit" class="btn" style="font-family: 'Open Sans', sans-serif;width: 100px;background: #0353D6; color: white !important;">
                                    Status <i class="fa icon-next"></i>
                                </button>
                            </div>
                        </div>
                    <script type="text/javascript">
                        jQuery(document).ready(function () {

                            $(".close-modal-refresh").click(function () {
                                location.reload();
                            });
                        });
                    </script>
 </form>
                </div>
            </div>
        </div>

{% endblock %}